language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator
xcode_workspace: Simlar.xcworkspace
xcode_scheme: Simlar
script:
- set -o pipefail
- xcodebuild -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" clean build | xcpretty
